version: '3.8'
services:
  app:
    image: blue_anonymous_bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=db    
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    depends_on:
      - prometheus
