package com.blue_farid.blue_anonymous_bot.model;

/**
 * the Client State class
 */
public enum ClientState {
    NORMAL, SENDING_MESSAGE_TO_SPECIFIC_CONTACT, SENDING_CONTACT_INFO, CHOOSING_CONTACT_GENDER, ADMIN_SENDING_CONTACT_ID, ADMIN_SENDING_CONTACT_INFO,
    SETTING_GENDER, SENDING_MESSAGE_TO_CONTACT, CONFIRM_STOP_CHAT, WAITING_FOR_CONTACT, SEND_TO_ALL;
}
